### ISSUE TITLE
The fullscreen mode is not working right

### ISSUE THREAD

**Issue by aggalex** [lainsce/quilter#105] opened 2017-11-25 15:40 UTC
When I open fullscreen mode (F11) on **Quilter 1.4.3** it has a rather... unexpected result. There is something wrong with it. You can see the unexpected behavior on the image below. The dark rectangle in the right is supposed to by fullscreen Quilter.

![screenshot from 2017-11-25 17 34 07](https://user-images.githubusercontent.com/11951328/33232000-93e9ffb0-d207-11e7-8048-f3d9150bedd9.png)

Dunno if useful, but me screen resolution is  1366x768

**Comment by lainsce** [comment] 2017-11-25 15:50
This is unresolvable since I don't know how people get into this state 95% of my users say fullscreen works 100%, so I don't get why you and 5% of my userbase get this bug. But, this bug isn't caused by Quilter itself, so, I'm sorry but it's a Won't Fix.

**Closed** 2017-11-25 15:51 UTC
Labels: invalid, wontfix

**Comment by lainsce** [comment] 2017-11-25 15:58
Also, just so you don't feel disheartened, can you tell me how did you get in this state? Did you hold the fullscreen button, or something else? Every detail matters.

**Comment by aggalex** [comment] 2017-11-25 16:29
No tricky stuff, just a single, normal tap on the F11 key created this behavior. Perhaps it has to do something with my obscure resolution (1366x768, with an aspect ratio of  683:384, which is the closes you can get to 16:9 by keeping the 768 pixels height from the older 1024x768 resolution with 4:3 aspect ratio. A resolution with height of 768 pixels and the aspect ratio of 16:9 should be around 1365.33 pixels wide, wich is impossible, thus the 1366.).

**Comment by lainsce** [comment] 2017-11-25 16:45
Hm, this sounds like a Gala issue then, since that's the thing that displays windows in elementary OS. Maybe file an issue there saying that in your resolution, fullscreen apps do not work?
