### ISSUE TITLE
Fail on maximize window

### ISSUE THREAD

**Issue by btd1337** [lainsce/quilter#27] opened 2017-07-02 02:17 UTC
The button Maximize doesn't works.

**Comment by lainsce** [comment] 2017-07-02 02:37
Duplicate of https://github.com/lainsce/quilter/issues/13

Sadly I can't fix this on my app, it's up to the window manager to be fixed
to support it for your use case, which is rare.

**Closed by lainsce** 2017-07-02 02:37 UTC
