### ISSUE TITLE
Find & replace -> Confirm with Enter in "Replace with..." field, should perform the action "Replace"

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#295] opened 2019-11-11 04:47 UTC
* Describe the issue
what it says on the tin!
Currently, Quilter does nothing when I press Enter.
* State what version you're using
2.0.3

**Comment by lainsce** [comment] 2019-11-25 20:06
I can reproduce this, going to fix it once I'm back.

**Comment by lainsce** [comment] 2019-11-27 12:37
Fixed with a tooltip on the replace button.

**Closed by lainsce** 2019-11-27 12:37 UTC
Labels: bug

**Comment by 4jNsY6fCVqZv** [comment] 2019-11-28 09:46
Is renaming a tooltip a solution or rather a workaround?
elementary code does that:
When I search for a string, say which word I want to replace it with and then press Enter, it automatically marks the first word that matches and replaces it. If there is a second word matching the string and I press Enter, it jumps to the next and replaces it with the desired replacement string.

**Comment by lainsce** [comment] 2019-11-28 12:41
It's a solution, because elementary Code does more with its replace behind the scenes than Quilter. It has to know where in the code it is, format it properly, etc. In Quilter, it's a simple swap between pieces of text.
