### ISSUE TITLE
Custom fonts are not applied to focus mode. Quilter: 1.3.8

### ISSUE THREAD

**Issue by Djcoper** [lainsce/quilter#93] opened 2017-10-21 04:33 UTC
![ezgif-1-b8e250a4f7](https://user-images.githubusercontent.com/30577249/31848059-35ca6ebc-b621-11e7-92c5-3693b0ae0a0a.gif)

**Comment by lainsce** [comment] 2017-10-21 09:07
That’s by design: “Focus Mode is 100% tailored to give focus to the text, it shouldn’t blink, have custom fonts, nor sudden rainbow text” — My design pages on the process of designing Quilter.
So this is a wontfix.

**Closed by lainsce** 2017-10-21 09:07 UTC
